### ISSUE TITLE
Add dotnet sdk convenience images

### ISSUE THREAD

**Issue by cdhunt** [CircleCI-Public/cimg-base#114]
Aligned with https://hub.docker.com/_/microsoft-dotnet-sdk

**Comment by Mint-6263** [comment]
@cdhunt

**Comment by cdhunt** [comment]
https://github.com/dotnet/dotnet-docker/tree/ca43690e6e4ac9c21a990a012dc2eb07e78daf08/src/sdk

**Comment by cdhunt** [comment]
I started a Dockerfile. If you can set up the repo and the build, I'm happy to contribute.

https://gist.github.com/cdhunt/9afb859d5ad2ff18beed0709b1f05521

**Comment by felicianotech** [comment]
Hi. Thank you for your request. We track new image requests on CircleCI Ideas. I see that you've already made a request there. Please share your request around to demonstrate customer need for this image so that we can prioritize it.

For anyone who comes across this issue, you can find the CircleCI Ideas request here: https://ideas.circleci.com/images/p/net-sdk-convenience-image

**Comment by shawnallen85** [comment]
I know this issue is closed as of now and there is the story on Ideas, but I put together a repo that is based off of the cimg-template repo: https://github.com/shawnallen85/cimg-dotnet/tree/dev/initial

**Comment by shawnallen85** [comment]
@felicianotech
