### ISSUE TITLE
`stable` tag does not have `docker-compose` installed

### ISSUE THREAD

**Issue by dcarter-ut** [CircleCI-Public/cimg-base#133]
```
docker pull cimg/base:stable && docker run --rm -it cimg/base:stable docker-compose --version
stable: Pulling from cimg/base
Digest: sha256:9d94b570bdd6809833d5e12d2ca1cb56de77d71dfe1d7e2fe44070b7fbbed048
Status: Image is up to date for cimg/base:stable
docker.io/cimg/base:stable
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "docker-compose": executable file not found in $PATH: unknown.
```
Vs`2021.11` tag:
```
docker pull cimg/base:2021.11 && docker run --rm -it cimg/base:2021.11 docker-compose --version
2021.11: Pulling from cimg/base
Digest: sha256:376c1dc2a8a549aa66c03ccd1c5efc8212e40b0d6138a1e465841a9dab8b1630
Status: Image is up to date for cimg/base:2021.11
docker.io/cimg/base:2021.11
docker-compose version 1.29.2, build 5becea4c
```

**Comment by felicianotech** [comment]
Starting with this month's base image release, Docker Compose is on v2 instead of v1. So instead of running `docker-compose` you'd run `docker compose`.

**Comment by felicianotech** [comment]
There's suppose to be what Docker calls Composer Switcher which aliases the two commands but when I tried to get it installed it wasn't working.

**Comment by dcarter-ut** [comment]
> Starting with this month's base image release, Docker Compose is on v2 instead of v1. So instead of running `docker-compose` you'd run `docker compose`.

fair enough; however I'd argue that a `stable` tag shouldn't change interfaces 🤷

**Comment by felicianotech** [comment]
The [readme for this image](https://github.com/CircleCI-Public/cimg-base#tagging-scheme) explains how the tags work. In short, `edge` gets updated whenever the default branch does. `stable` gets updated once a month. These will include changes from Ubuntu and any of the software we pre-install in the image. The tag is called stabled because it's not an alpha or beta, as the edge tag can be considered. The monthly snapshot tags should be used when it's desired for the underlying software versions not to change.
