### ISSUE TITLE
Docker image 20.04 and 18.04 no more pushed on Docker Hub

### ISSUE THREAD

**Issue by PerfectSlayer** [CircleCI-Public/cimg-base#223]
Hello,

Quick question: I can see from [your Docker Hub tags](https://hub.docker.com/r/cimg/base/tags?page=1&name=edge) the Ubuntu `18.04` and `20.04` are no more updated.
And this commit  927a2741b27f6a01bd14bc71e1a88eb10a82ef3d removed their push to the registry.

Is it on purpose? Did you drop the support for the older Ubuntu versions?
If not, can you trigger a build/push to update them on Docker Hub please? I would like to have the latest security fixes for `yq` and `docker-compose`. Thanks

Best,
Bruce

**Comment by felicianotech** [comment]
Hey.

Great catch. So I did some digging and there seems to be a bug here. We do support builds for 18.04, 20.04, and 22.04 still. 18.04 might be dropped in the near future but otherwise, they are supported.

The `current` tag still has all three built and so does the monthly snapshots (i.e. `2022.12-20.04`, etc). It's just the edge tag that has this broken. Will fix very soon.

**Comment by PerfectSlayer** [comment]
Thanks for the feedback!

**Comment by felicianotech** [comment]
Clearly I misjudged what "very soon is". I aim to have this complete this week. In the meantime, `current` and `2023.01` will be available later today will updates.
