### ISSUE TITLE
Include the CircleCI CLI?

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/cimg-base#50]
@KyleTryon and I had a discussion on the CircleCI CLI within CircleCI builds. Right now, it may look like the CLI is installed on every build but this is a portion of the CLI that is injected at runtime.

Currently none of our images, legacy or next-gen, pre-installs the CircleCI CLI. Should we?

Two cons I can think of:
- more MBs of space taken in the image
- the CLI at times updates frequently, this image will update monthly

A pro:
- orb development - the pack and publish commands are important

Anything else to add @CircleCI-Public/cpeng?

**Comment by KyleTryon** [comment]
Because we inject some version of the CLI I am worried how this could potentially affect current users. As you mentioned above it is highly useful for orb development but perhaps not all users. We also have our orb to install the CLI if needed. I think we could revisit this but it is not essential at the moment.

**Comment by felicianotech** [comment]
Makes sense to me.
