### ISSUE TITLE
Include psql?

### ISSUE THREAD

**Issue by nashbridges** [CircleCI-Public/cimg-base#91]
Related to https://github.com/CircleCI-Public/cimg-base/pull/61

Is it possible to also include postgresql-client package?
`psql` executable is used under the hood in the `bundle exec db:structure:load` task in Rails. 

It fails with the ruby-2.6-node image:

![image](https://user-images.githubusercontent.com/380913/106360439-16a64c80-6321-11eb-95f8-502a306d5757.png)

**Comment by nashbridges** [comment]
Current recommended approach is to install `psql` on each run with a [manual command](https://circleci.com/docs/2.0/postgres-config/)

```
- run: sudo apt install -y postgresql-client || true
```

or with a [3rd party orb](https://circleci.com/developer/orbs/orb/onehq/postgres).

As a side note, the [suggested command](https://circleci.com/docs/2.0/postgres-config/) should be updated to

```
- run: sudo apt-get update && sudo apt install -y postgresql-client
```

Otherwise

a) it fails with the "E: Unable to locate package postgresql-client" error
b) when it fails it does not stop the build

Both approaches (the manual one and with the orb) have the same drawbacks:

1) they don't benefit from Docker's fs caching. That means more HTTP requests are made, and every request can potentially fail the build due to a network error 
2) they spend CircleCI credits (which is especially important for public repos with free credits)

The alternative (which is also mentioned in [the docs](https://circleci.com/developer/orbs/orb/onehq/postgres)) is to maintain and host your own Docker image with `psql` preinstalled. Although it does not have the drawbacks from above, it requires a significant amount of effort from devs. I assume that was the main reason for #61 ("[we want something that works](https://github.com/CircleCI-Public/cimg-base/issues/60#issuecomment-622148304)").

I do understand that you can not satisfy every dev in the world, but perhaps the top X popular databases? 

An alternative to put everything into one base image would be to have the "-pg", "-mysql" etc prefixes similar to existing "-node" (although I understand it will boost the number of image variations).

**Comment by gmemstr** [comment]
I'll let @felicianotech speak further/correct me on this, but initial reaction is that this is something better kept in either the config using apt get, or a custom Docker image. While I can see the upside of adding `psql` to the base image, we would also include the other clients, which I'm unsure is something we'd want to do. Creating variants doesn't feel quite right either.

I would argue that maintaining a Docker image based on `cimg/base` with specific dependencies is a much less brittle way of including them within your pipelines, since you'll have full control over the version of dependencies installed (say you rely on `cimg/base:stable-pg`, and there's a breaking change to postgres for whatever reason and we upgrade). Curious what you mean by "significant amount of effort from devs" - unless upgrading or adding a dependency, a Docker image will be pretty low maintenance.

Keeping these images generic enough to fit most use cases while also having the flexibility to be moulded to specific needs is more or less an end goal of our convenience images, and adding SQL/NoSQL clients to the mix might shake that up a bit too much.
